### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by pdcemulator** [weltenwort/py-hpsu-monitor#90]
Hello,
I tried to setup py-hpsu-monitor, but I can't get it running. Its installed on a RaspberryPi 2 running latest Bullseye. The dependencies are also installed.
```
root@raspberrypi:~/py-hpsu-monitor# poetry debug

Poetry
Version: 1.1.12
Python:  3.9.2

Virtualenv
Python:         3.9.2
Implementation: CPython
Path:           /root/.cache/pypoetry/virtualenvs/py-hpsu-monitor-oKw-sLrK-py3.9
Valid:          True

System
Platform: linux
OS:       posix
Python:   /usr
```

[removed]

Edit: got it running using the command `poetry run py-hpsu-monitor run`.

Which one is the name for the config file?
default-config.toml and config.toml dir not work, it tried to connect to broker on localhost even when I configured other server names. So I edited MQTT details in py_hpsu_monitor/config.py and finally got it running.
I will do some tests and then submit a PR with more installation details.

**Comment by weltenwort** [comment]
Hi @pdcemulator, thanks for trying it out. You're the first person I know of who deploys this besides myself. :see_no_evil:

I have PR #60 open which contains some changes to the configuration and a `Dockerfile` to ease deployment. I hope I can merge it today and update the README to include more deployment instructions to help you out.

**Comment by weltenwort** [comment]
I have merged the PR and added more installation documentation. Please let me know if anything remains unclear or if I can help with anything.

**Comment by pdcemulator** [comment]
It has been running for over a week now. Seems stable and runs parallel with pyHPSU and a Rotex HPSU compact 506 from 2015. Thank you for sharing this.

Some of the temperature values are very long (27.700000000000003), they should be rounded.
Could you add additional values like operating Mode (heating, cooling, off) and the current mode (heating, defrost, warm water)?

I also tried the latest version today, but I do not see the new writable entities in home assistant (Developer Tab and with my MQTT monitor). And I would like to activate hot water generation if this is possible.

**Comment by weltenwort** [comment]
Glad to hear it mostly works :smile: 

> Some of the temperature values are very long (27.700000000000003), they should be rounded.

That looks like a IEEE 754 floating point representation problem. I'll have to analyze whether this happens here or in Home Assistant.

> Could you add additional values like operating Mode (heating, cooling, off) and the current mode (heating, defrost, warm water)?

Yes, I'd like to add that, but didn't get around to it yet.

> I do not see the new writable entities in home assistant

They should show up as `number` entities. Can you check on the HA device page?

![image](https://user-images.githubusercontent.com/973741/152707124-cd4451aa-46f8-434a-a62e-5293f8019a3e.png)

> And I would like to activate hot water generation if this is possible.

I'm currently doing that in response to PV over-production using a HA automation that sets the target temperature to something high (like 60 °C). I know there must be a way to trigger the HW generation using a command, but I haven't found it yet. Do you have any resources that can help to decode the commands?

These are all good feature requests, thank you. I can't guarantee when I'll have the time to tackle them, but there's always hope. :wink: PRs are also welcome if you feel like it
